version: "3.7"

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    command: npm run dev
    env_file: .env
    environment:
      - DB_HOST=database
      - DB_NAME=backend
      - DB_TYPE=mysql
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - database
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/nodemon.json:/home/node/app/nodemon.json
    network_mode: bridge

  database:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    network_mode: bridge
